# Generated by Django 4.1.7 on 2023-03-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('ACTION', 'ACTION'), ('HORROR', 'HORROR'), ('COMEDY', 'COMEDY')], max_length=255)),
                ('actors', models.ManyToManyField(to='BookMyShow.actor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('seat_status', models.CharField(choices=[('BROKEN', 'BROKEN'), ('AVAILABLE', 'AVAILABLE')], max_length=255)),
                ('seat_auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.auditorium')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('show_features', models.CharField(blank=True, choices=[('TWO_D', '2D'), ('THREE_D', 'THREE_D'), ('AC_HALL', 'AC_HALL')], max_length=100)),
                ('show_auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.auditorium')),
                ('show_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('show_seat_status', models.CharField(choices=[('BOOKED', 'BOOKED'), ('LOCKED', 'LOCKED'), ('UNAVAILABLE', 'UNAVAILABLE'), ('AVAILABLE', 'AVIALABLE')], max_length=255)),
                ('show_seat_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.seat')),
                ('show_seat_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField()),
                ('ticket_status', models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('BOOKED', 'BOOKED'), ('PAYMENT_PENDING', 'PAYMENT_PENDING')], max_length=255)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BookMyShow.user')),
                ('show_seats', models.ManyToManyField(to='BookMyShow.showseat')),
                ('ticket_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('theatre_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowSeatType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('seat_type', models.CharField(choices=[('GOLD', 'GOLD'), ('SILVER', 'SILVER')], max_length=255)),
                ('type_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='showseat',
            name='show_seat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.showseattype'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('CREDIT_CARD', 'CREDIT_CARD'), ('UPI', 'UPI'), ('CASH', 'CASH')], max_length=255)),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('DONE', 'DONE')], max_length=255)),
                ('payment_time', models.DateTimeField()),
                ('reference_id', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('payment_ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BookMyShow.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='auditorium',
            name='theatre_audi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoriums', to='BookMyShow.theatre'),
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(to='BookMyShow.movie'),
        ),
    ]
