# Generated by Django 4.1.7 on 2023-03-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('features', models.CharField(blank=True, choices=[('TWO_D', '2D'), ('THREE_D', '3D'), ('DOLBY', 'DOLBY')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('genres', models.CharField(blank=True, choices=[('COMEDY', 'COMEDY'), ('HORRO', 'HORROR')], max_length=100)),
                ('features', models.CharField(blank=True, choices=[('TWO_D', '2D'), ('THREE_D', '3D'), ('DOLBY', 'DOLBY')], max_length=100)),
                ('actors', models.ManyToManyField(to='BookMyShow.actor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('seat_status', models.CharField(blank=True, choices=[('available', 'AVAILABLE'), ('unavailable', 'UNAVAILABLE')], max_length=100)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.auditorium')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('show_features', models.CharField(blank=True, choices=[('TWO_D', '2D'), ('THREE_D', '3D'), ('DOLBY', 'DOLBY')], max_length=100)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.auditorium')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField()),
                ('ticket_status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('BOOKED', 'BOOKED')], max_length=100)),
                ('time_of_booking', models.DateTimeField()),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.user')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.show')),
                ('show_seats', models.ManyToManyField(to='BookMyShow.showseat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowSeatType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('seat_type', models.CharField(choices=[('GOLD', 'GOLD'), ('SILVER', 'SILVER')], max_length=10)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_time', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('reference_id', models.CharField(max_length=255)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='auditorium',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyShow.theatre'),
        ),
    ]
